/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.unifae.engsof.poo3.gerenciadorDeTarefas.view;

import br.unifae.engsof.poo3.gerenciadorDeTarefas.controller.TarefaController;

/**
 *
 * @author android
 */
public class ListarView extends javax.swing.JFrame {
    TarefaController tarefa_controller = new TarefaController();
    /**
     * Creates new form ListarView
     */
    public ListarView() {
        initComponents();
        
        tarefa_controller.show(tabela_tarefas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_tarefas = new javax.swing.JTable();
        button_excluir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_cadastrar = new javax.swing.JMenu();
        tarefa_simples = new javax.swing.JMenuItem();
        tarefa_com_prazo = new javax.swing.JMenuItem();
        menu_listar = new javax.swing.JMenu();
        menu_buscar = new javax.swing.JMenu();
        menu_sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("Tarefas");

        tabela_tarefas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Descrição", "Prioridade", "Data de criação", "Prazo", "Concluida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela_tarefas);

        button_excluir.setText("Excluir");
        button_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_excluirActionPerformed(evt);
            }
        });

        menu_cadastrar.setText("Cadastrar");
        menu_cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tarefa_simples.setText("Tarefa simples");
        tarefa_simples.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tarefa_simples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarefa_simplesActionPerformed(evt);
            }
        });
        menu_cadastrar.add(tarefa_simples);

        tarefa_com_prazo.setText("Tarefa com prazo");
        tarefa_com_prazo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tarefa_com_prazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarefa_com_prazoActionPerformed(evt);
            }
        });
        menu_cadastrar.add(tarefa_com_prazo);

        jMenuBar1.add(menu_cadastrar);

        menu_listar.setText("Listar");
        menu_listar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu_listar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_listarMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_listar);

        menu_buscar.setText("Buscar");
        menu_buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_buscarMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_buscar);

        menu_sair.setText("Sair");
        menu_sair.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_sairMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(375, 375, 375)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button_excluir)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tarefa_simplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarefa_simplesActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TarefaSimplesView tarefa_simples = new TarefaSimplesView();
        tarefa_simples.setVisible(true);
    }//GEN-LAST:event_tarefa_simplesActionPerformed

    private void tarefa_com_prazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarefa_com_prazoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TarefaComPrazoView tarefa_com_prazo = new TarefaComPrazoView();
        tarefa_com_prazo.setVisible(true);
    }//GEN-LAST:event_tarefa_com_prazoActionPerformed

    private void menu_listarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_listarMouseClicked
        // TODO add your handling code here:
        this.dispose();
        ListarView listar = new ListarView();
        listar.setVisible(true);
    }//GEN-LAST:event_menu_listarMouseClicked

    private void menu_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_buscarMouseClicked
        // TODO add your handling code here:
        this.dispose();
        BuscarView buscar = new BuscarView();
        buscar.setVisible(true);
    }//GEN-LAST:event_menu_buscarMouseClicked

    private void menu_sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_sairMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menu_sairMouseClicked

    private void button_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_excluirActionPerformed
        // TODO add your handling code here:
        tarefa_controller.delete(tabela_tarefas);
    }//GEN-LAST:event_button_excluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_excluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menu_buscar;
    private javax.swing.JMenu menu_cadastrar;
    private javax.swing.JMenu menu_listar;
    private javax.swing.JMenu menu_sair;
    private javax.swing.JTable tabela_tarefas;
    private javax.swing.JMenuItem tarefa_com_prazo;
    private javax.swing.JMenuItem tarefa_simples;
    // End of variables declaration//GEN-END:variables
}
