/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.unifae.engsof.poo3.gerenciadorDeTarefas.view;

import br.unifae.engsof.poo3.gerenciadorDeTarefas.controller.TarefaController;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author android
 */
public class TarefaComPrazoView extends javax.swing.JFrame {
    TarefaController tarefa = new TarefaController();
    /**
     * Creates new form TarefaSimples
     */
    public TarefaComPrazoView() {
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        input_descricao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        input_data_criacao = new javax.swing.JFormattedTextField();
        input_prioridade = new javax.swing.JComboBox<>();
        label_prazo = new javax.swing.JLabel();
        input_prazo = new javax.swing.JFormattedTextField();
        btnCadastrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_cadastrar = new javax.swing.JMenu();
        tarefa_simples = new javax.swing.JMenuItem();
        tarefa_com_prazo = new javax.swing.JMenuItem();
        menu_listar = new javax.swing.JMenu();
        menu_buscar = new javax.swing.JMenu();
        menu_sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Obrigatórios"));
        jPanel1.setToolTipText("");

        input_descricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_descricaoActionPerformed(evt);
            }
        });

        jLabel1.setLabelFor(input_descricao);
        jLabel1.setText("Descrição");

        jLabel3.setLabelFor(input_data_criacao);
        jLabel3.setText("Data criação");

        jLabel2.setLabelFor(input_prioridade);
        jLabel2.setText("Prioridade");

        try {
            input_data_criacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        input_data_criacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_data_criacaoActionPerformed(evt);
            }
        });

        input_prioridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        label_prazo.setLabelFor(input_data_criacao);
        label_prazo.setText("Prazo");

        try {
            input_prazo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        input_prazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_prazoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label_prazo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(input_prazo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input_data_criacao, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input_prioridade, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(input_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_prioridade, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_data_criacao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_prazo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_prazo))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setText("Tarefa com prazo");

        menu_cadastrar.setText("Cadastrar");
        menu_cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tarefa_simples.setText("Tarefa simples");
        tarefa_simples.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tarefa_simples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarefa_simplesActionPerformed(evt);
            }
        });
        menu_cadastrar.add(tarefa_simples);

        tarefa_com_prazo.setText("Tarefa com prazo");
        tarefa_com_prazo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tarefa_com_prazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarefa_com_prazoActionPerformed(evt);
            }
        });
        menu_cadastrar.add(tarefa_com_prazo);

        jMenuBar1.add(menu_cadastrar);

        menu_listar.setText("Listar");
        menu_listar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu_listar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_listarMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_listar);

        menu_buscar.setText("Buscar");
        menu_buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_buscarMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_buscar);

        menu_sair.setText("Sair");
        menu_sair.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_sairMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btnCadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel5)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tarefa_simplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarefa_simplesActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TarefaSimplesView tarefa_simples = new TarefaSimplesView();
        tarefa_simples.setVisible(true);
    }//GEN-LAST:event_tarefa_simplesActionPerformed

    private void tarefa_com_prazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarefa_com_prazoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TarefaComPrazoView tarefa_com_prazo = new TarefaComPrazoView();
        tarefa_com_prazo.setVisible(true);
    }//GEN-LAST:event_tarefa_com_prazoActionPerformed

    private void menu_listarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_listarMouseClicked
        // TODO add your handling code here:
        this.dispose();
        ListarView listar = new ListarView();
        listar.setVisible(true);
    }//GEN-LAST:event_menu_listarMouseClicked

    private void menu_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_buscarMouseClicked
        // TODO add your handling code here:
        this.dispose();
        BuscarView buscar = new BuscarView();
        buscar.setVisible(true);
    }//GEN-LAST:event_menu_buscarMouseClicked

    private void menu_sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_sairMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menu_sairMouseClicked

    private void input_prazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_prazoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_prazoActionPerformed

    private void input_data_criacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_data_criacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_data_criacaoActionPerformed

    private void input_descricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_descricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_descricaoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
        TarefaView tarefa_view = new TarefaView();
        tarefa_view.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        try{
            LocalDate.parse(input_data_criacao.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            LocalDate.parse(input_prazo.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Data inválida", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String descricao = input_descricao.getText();
        int prioridade = Integer.parseInt(String.valueOf(input_prioridade.getSelectedItem()));
        LocalDate data_criacao = LocalDate.parse(input_data_criacao.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        LocalDate prazo = LocalDate.parse(input_prazo.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy"));

        if(tarefa.create(descricao, prioridade, data_criacao, prazo)){
            JOptionPane.showMessageDialog(rootPane, "Tarefa criada com sucesso!");
            input_descricao.setText(null);
            input_prioridade.setSelectedItem("1");
            input_data_criacao.setText(null);
            input_prazo.setText(null);
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Não foi possível criar a tarefa", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TarefaComPrazoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TarefaComPrazoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TarefaComPrazoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TarefaComPrazoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TarefaComPrazoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JFormattedTextField input_data_criacao;
    private javax.swing.JTextField input_descricao;
    private javax.swing.JFormattedTextField input_prazo;
    private javax.swing.JComboBox<String> input_prioridade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_prazo;
    private javax.swing.JMenu menu_buscar;
    private javax.swing.JMenu menu_cadastrar;
    private javax.swing.JMenu menu_listar;
    private javax.swing.JMenu menu_sair;
    private javax.swing.JMenuItem tarefa_com_prazo;
    private javax.swing.JMenuItem tarefa_simples;
    // End of variables declaration//GEN-END:variables
}
